# swagger.yml

openapi: 3.0.0
info:
  title: "Mobility-Station-Finder API"
  description: "An API to get best Mobility-stations for your journey"
  version: "1.0.0"
  
servers:
  - url: "/api"

paths:
  /npvm-zone/{coords}:
    get:
      summary: "Get the NPVM-zone from a point in Switzerland"
      operationId: model.get_npvm_zone
      parameters:
        - name: coords
          in: path
          required: true
          description: "Coordinates in WGS84"
          schema:
            type: string
      responses:
        "200":
          description: "Successfully read NPVM zone"


          