# swagger.yml

openapi: 3.0.0
info:
  title: "Mobility-Station-Finder API"
  description: "An API to get best Mobility-stations for your journey"
  version: "1.0.0"
  
servers:
  - url: "/api"

components:
  schemas:
    Coordinates:
      type: object
      required:
        - easting
        - northing
      properties:
        easting:
          type: number
        northing:
          type: number
  parameters:
    coords:
      name: coords
      description: "Coordinates in WGS84"
      in: path
      required: true
      schema:
        type: object  

paths:
  /npvm-zone/{coords}:
    get:
      operationId: model.get_npvm_zone
      tags:
        - Coordinates
      summary: "Get the NPVM-zone from a point in Switzerland"
      parameters:
        - $ref: "#/components/parameters/coords"
      responses:
        "200":
          description: "Successfully read NPVM zone"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "coord"
              $ref: "#/components/schemas/Coordinates"


          