# swagger.yml

openapi: 3.0.0
info:
  title: "Mobility-Station-Finder API"
  description: "An API to get the best Mobility-stations for your journey"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /npvm-zone:
    get:
      tags:
        - npvm-zone
      summary: "Get the NPVM-zone from a point in Switzerland"
      operationId: msf_flask_app.model.get_npvm_zone
      parameters:
        - name: easting
          in: query
          description: "Longitude in WGS84"
          required: true
          schema:
            type: number
        - name: northing
          in: query
          description: "Latitude in WGS84"
          required: true
          schema:
            type: number


      responses:
        "200":
          description: "Successfully read NPVM zone"


          